-- MySQL Script generated by MySQL Workbench
-- Fri Sep 27 14:08:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Prova
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Prova
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Prova` ;
USE `Prova` ;

-- -----------------------------------------------------
-- Table `Prova`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova`.`Produtos` (
  `cod_barras` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `qtd` INT NOT NULL,
  PRIMARY KEY (`cod_barras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova`.`Vendas` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova`.`Vendas_has_Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova`.`Vendas_has_Produtos` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `qtd` INT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `Vendas_cod` INT NOT NULL,
  `Produtos_cod_barras` INT NOT NULL,
  PRIMARY KEY (`cod`, `Vendas_cod`, `Produtos_cod_barras`),
  INDEX `fk_Vendas_has_Produtos_Produtos1_idx` (`Produtos_cod_barras` ASC),
  INDEX `fk_Vendas_has_Produtos_Vendas_idx` (`Vendas_cod` ASC),
  CONSTRAINT `fk_Vendas_has_Produtos_Vendas`
    FOREIGN KEY (`Vendas_cod`)
    REFERENCES `Prova`.`Vendas` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_cod_barras`)
    REFERENCES `Prova`.`Produtos` (`cod_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/* Prova 27/09/2007 */
-- 1)
Select P.nome from Itens_vendas as I
inner join Produtos as P on (I.Produtos_cod_barras = P.cod_barras)
inner join Vendas as V on (I.Vendas_cod = V.cod);

-- 2)
Select I.cod, I.qtd, I.preco, P.nome, V.data from Itens_vendas as I
inner join Produtos as P on (I.Produtos_cod_barras = P.cod_barras)
inner join Vendas as V on (I.Vendas_cod = V.cod)
where P.nome = "Toddy";

-- 3)
Select I.cod, I.qtd, I.preco, P.nome, V.data from Itens_vendas as I
inner join Produtos as P on (I.Produtos_cod_barras = P.cod_barras )
inner join Vendas as V on (I.Vendas_cod = V.cod)
where month(V.data) = "05";

-- 4)
Select P.nome from Itens_vendas as I
inner join Produtos as P on (I.Produtos_cod_barras = P.cod_barras)
inner join Vendas as V on (I.Vendas_cod = V.cod)
;

-- 6)
Select P.nome, sum(I.qtd) as "Total de vendas", V.data from Itens_vendas as I
inner join Produtos as P on (I.Produtos_cod_barras = P.cod_barras)
inner join Vendas as V on (I.Vendas_cod = V.cod)
where month(V.data) = "05"
group by P.nome
order by "Total de vendas" DESC;

-- 7)
Select count(I.cod) as "Total de vendas", V.data from Itens_vendas as I
inner join Produtos as P on (I.Produtos_cod_barras = P.cod_barras)
inner join Vendas as V on (I.Vendas_cod = V.cod)
where month(V.data) = "05";

-- 8)
Select avg(TotalPorDia.TotalVendidoDia) as MediaVendasPorDia from (select Vendas.data, sum(Itens_vendas.qtd) as TotalVendidoDia from Vendas
inner join Itens_vendas on Vendas.cod = Itens_vendas.Vendas_cod
where month(Vendas.data) = "05"
group by Vendas.data) as TotalPorDia;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
