/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Utils.DisciplinaDAO;
import Utils.DisciplinaDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno.Tarde
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGEnsino = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jRTecnico = new javax.swing.JRadioButton();
        jRFundamental1 = new javax.swing.JRadioButton();
        jRFundamental2 = new javax.swing.JRadioButton();
        jRMedio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jBSalvar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBDeletar = new javax.swing.JButton();
        jBPesquisar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jSCargaHoraria = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de disciplina");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jTNome.setBackground(new java.awt.Color(51, 51, 51));
        jTNome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 238, -1));

        bGEnsino.add(jRTecnico);
        jRTecnico.setForeground(new java.awt.Color(255, 255, 255));
        jRTecnico.setText("Técnico");
        jPanel1.add(jRTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        bGEnsino.add(jRFundamental1);
        jRFundamental1.setForeground(new java.awt.Color(255, 255, 255));
        jRFundamental1.setText("Fundamental 1");
        jRFundamental1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRFundamental1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRFundamental1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        bGEnsino.add(jRFundamental2);
        jRFundamental2.setForeground(new java.awt.Color(255, 255, 255));
        jRFundamental2.setText("Fundamental 2");
        jPanel1.add(jRFundamental2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        bGEnsino.add(jRMedio);
        jRMedio.setForeground(new java.awt.Color(255, 255, 255));
        jRMedio.setText("Médio");
        jPanel1.add(jRMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel2.setText("Ensino:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jBSalvar.setBackground(new java.awt.Color(51, 102, 255));
        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        jBSair.setBackground(new java.awt.Color(255, 51, 51));
        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });
        jPanel1.add(jBSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 100, -1));

        jBCancelar.setBackground(new java.awt.Color(255, 51, 51));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 90, -1));

        jBDeletar.setBackground(new java.awt.Color(255, 51, 51));
        jBDeletar.setText("Deletar");
        jBDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(jBDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 90, -1));

        jBPesquisar.setBackground(new java.awt.Color(51, 102, 255));
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jBPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jBAlterar.setBackground(new java.awt.Color(51, 102, 255));
        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(jBAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));
        jPanel1.add(jSCargaHoraria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 187, -1, 30));

        jLabel3.setText("Carga horária:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private int idDisciplina;
    
    private void deletarCampos(){
        jTNome.setText("");
        jSCargaHoraria.setValue(0);
        jRFundamental1.setSelected(false);
        jRFundamental2.setSelected(false);
        jRMedio.setSelected(false);
        jRTecnico.setSelected(false);
    }
    
    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jRFundamental1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRFundamental1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRFundamental1ActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        deletarCampos();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:
        try{
            String nome = jTNome.getText();
            int cargaHoraria = Integer.parseInt(jSCargaHoraria.getValue().toString());
            String ensino = null;
            
            if(jRFundamental1.isSelected()){
                ensino = "Fundamental1";
            }
            if(jRFundamental2.isSelected()){
                ensino = "Fundamental2";
            }
            if(jRMedio.isSelected()){
                ensino = "Medio";
            }
            if(jRTecnico.isSelected()){
                ensino = "Tecnico";
            }
            
            if(ensino != null){
                DisciplinaDTO disciplinaDTO = new DisciplinaDTO();
                disciplinaDTO.setNome(nome);
                disciplinaDTO.setCargaHoraria(cargaHoraria);
                disciplinaDTO.setEnsino(ensino);
                
                DisciplinaDAO disciplinaDAO = new DisciplinaDAO();
                int response = disciplinaDAO.cadastrarDisciplina(disciplinaDTO);
                
                if(response != -1){
                    JOptionPane.showMessageDialog(rootPane, "Cadastro efetuado com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(rootPane, "ERRO: cadastro negado.");
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERRO: dados inválidos");
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:
        try{
            String nome = jTNome.getText();
            
            DisciplinaDTO disciplinaDTO = new DisciplinaDTO();
            disciplinaDTO.setNome(nome);
            
            DisciplinaDAO disciplinaDAO = new DisciplinaDAO();
            disciplinaDTO = disciplinaDAO.localizarProdutos(disciplinaDTO.getNome());
            
            if (disciplinaDTO != null){
                jTNome.setText(disciplinaDTO.getNome());
                jSCargaHoraria.setValue(disciplinaDTO.getCargaHoraria());
                this.idDisciplina = disciplinaDTO.getIdDisciplina();
                
                if(disciplinaDTO.getEnsino().equals("Fundamental1")){
                    jRFundamental1.setSelected(true);
                }
                if(disciplinaDTO.getEnsino().equals("Fundamental2")){
                    jRFundamental2.setSelected(true);
                }
                if(disciplinaDTO.getEnsino().equals("Medio")){
                    jRMedio.setSelected(true);
                }
                if(disciplinaDTO.getEnsino().equals("Tecnico")){
                    jRTecnico.setSelected(true);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "ERRO: pesquisa negada.");
                System.out.println(disciplinaDTO);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERRO: dados inválidos.");
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        // TODO add your handling code here:
        try{
            String nome = jTNome.getText();
            int cargaHoraria = Integer.parseInt(jSCargaHoraria.getValue().toString());
            int idDisciplina = this.idDisciplina;
            String ensino = null;

                if(jRFundamental1.isSelected()){
                    ensino = "Fundamental1";
                }
                if(jRFundamental2.isSelected()){
                    ensino = "Fundamental2";
                }
                if(jRMedio.isSelected()){
                    ensino = "Medio";
                }
                if(jRTecnico.isSelected()){
                    ensino = "Tecnico";
                }

                if(ensino != null){
                    DisciplinaDTO disciplinaDTO = new DisciplinaDTO();
                    disciplinaDTO.setIdDisciplina(idDisciplina);
                    disciplinaDTO.setNome(nome);
                    disciplinaDTO.setCargaHoraria(cargaHoraria);
                    disciplinaDTO.setEnsino(ensino);
                    
                    DisciplinaDAO disciplinaDAO = new DisciplinaDAO();
                    int response = disciplinaDAO.alterarDisciplina(disciplinaDTO); 
                    
                    if(response != -1){
                        JOptionPane.showMessageDialog(rootPane, "Alteração efetuada com sucesso!");
                    }else{
                        System.out.println(response);
                        JOptionPane.showMessageDialog(rootPane, "ERRO: alteração negada.");
                    }
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERRO: dados inválidos.");
        }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeletarActionPerformed
        // TODO add your handling code here:
        try{
            int idDisciplina = this.idDisciplina;
            
            DisciplinaDAO disciplinaDAO = new DisciplinaDAO();
            int response = disciplinaDAO.deletarDisciplina(idDisciplina);
            
            if(response != -1){
                JOptionPane.showMessageDialog(rootPane, "Deletado com sucesso");
                deletarCampos();
            }else{
                JOptionPane.showMessageDialog(rootPane, "ERRO: deletar negado");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERRO: dados inválidos.");
        }
    }//GEN-LAST:event_jBDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGEnsino;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBDeletar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRFundamental1;
    private javax.swing.JRadioButton jRFundamental2;
    private javax.swing.JRadioButton jRMedio;
    private javax.swing.JRadioButton jRTecnico;
    private javax.swing.JSpinner jSCargaHoraria;
    private javax.swing.JTextField jTNome;
    // End of variables declaration//GEN-END:variables
}
