/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.DAOAcesso;
import DAO.DAOSenha;
import Model.CSenha;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno.Tarde
 */
public class jFrmSenha extends javax.swing.JFrame {

    /**
     * Creates new form jFrmSenha
     */
    public jFrmSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBLogin = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jTSenha = new javax.swing.JTextField();
        JLPrimeiroAcesso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Usuário:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 112, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Senha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 161, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Realize seu Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jTUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 111, 227, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 10, 40));

        jBLogin.setBackground(new java.awt.Color(51, 51, 51));
        jBLogin.setForeground(new java.awt.Color(204, 204, 204));
        jBLogin.setText("Login");
        jBLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLoginMouseExited(evt);
            }
        });
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jBLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 93, 110, 48));

        jBCancelar.setBackground(new java.awt.Color(51, 51, 51));
        jBCancelar.setForeground(new java.awt.Color(204, 204, 204));
        jBCancelar.setText("Cancelar");
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBCancelarMouseExited(evt);
            }
        });
        jPanel1.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 159, 110, 48));

        jTSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(jTSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 160, 227, -1));

        JLPrimeiroAcesso.setForeground(new java.awt.Color(153, 153, 153));
        JLPrimeiroAcesso.setText("Primeiro acesso?");
        JLPrimeiroAcesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLPrimeiroAcessoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLPrimeiroAcessoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLPrimeiroAcessoMouseExited(evt);
            }
        });
        jPanel1.add(JLPrimeiroAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 205, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUsuarioActionPerformed

    private void jTSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSenhaActionPerformed

    private void JLPrimeiroAcessoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLPrimeiroAcessoMouseClicked
        // TODO add your handling code here:
        jFrmPrimeiroAcesso PrimeiroAcesso = new jFrmPrimeiroAcesso();
        PrimeiroAcesso.setVisible(true);
        dispose();
    }//GEN-LAST:event_JLPrimeiroAcessoMouseClicked

    private void JLPrimeiroAcessoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLPrimeiroAcessoMouseEntered
        // TODO add your handling code here:
        JLPrimeiroAcesso.setForeground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_JLPrimeiroAcessoMouseEntered

    private void JLPrimeiroAcessoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLPrimeiroAcessoMouseExited
        // TODO add your handling code here:
        JLPrimeiroAcesso.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_JLPrimeiroAcessoMouseExited

    private void jBLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLoginMouseEntered
        // TODO add your handling code here:
        jBLogin.setBackground(new java.awt.Color(0,51,255));
    }//GEN-LAST:event_jBLoginMouseEntered

    private void jBLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLoginMouseExited
        // TODO add your handling code here:
        jBLogin.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBLoginMouseExited

    private void jBCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseExited
        // TODO add your handling code here:
        jBCancelar.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBCancelarMouseExited

    private void jBCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseEntered
        // TODO add your handling code here:
        jBCancelar.setBackground(new java.awt.Color(255,51,51));
    }//GEN-LAST:event_jBCancelarMouseEntered

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        // TODO add your handling code here:
        DAOAcesso daoAcesso = new DAOAcesso();
        DAOSenha daoSenha = new DAOSenha();
            
        String usuario = jTUsuario.getText();
        String senha = jTSenha.getText();

        try{
            //Instancia um novo CSenha que vai receber o ruturn do DAOSenha
            CSenha cSenha = daoSenha.LocalizarCsenha(usuario);
            
            if(cSenha != null){
                if(senha.equals(cSenha.getSenha())){
                    jFrmSenha jFrmSenha = new jFrmSenha();
                    jFrmSenha.setVisible(true);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "As senhas não conferem");
                }
            }else{
                System.out.println("cSenha null");
            }
            jFrmProjeto jFrmProjeto = new jFrmProjeto();
            jFrmProjeto.setVisible(true);
            dispose();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "A senha não confere: " + ex.getMessage());
            jTUsuario.setText("");
            jTSenha.setText("");
        }
    }//GEN-LAST:event_jBLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Cupertino Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLPrimeiroAcesso;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTSenha;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
