/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.DAOAcesso;
import DAO.DAOSenha;
import Model.CAcesso;
import java.sql.SQLException;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno.Tarde
 */
public class jFrmPrimeiroAcesso extends javax.swing.JFrame {

    /**
     * Creates new form jFrmPrimeiroAcesso
     */
    public jFrmPrimeiroAcesso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTNumero = new javax.swing.JTextField();
        jTEndereco = new javax.swing.JTextField();
        jTBairro = new javax.swing.JTextField();
        jTMunicipio = new javax.swing.JTextField();
        jTNome = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jBConcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPSenha = new javax.swing.JPasswordField();
        jPConfirmarSenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Endereço:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Município:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Bairro:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Número:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Registrar a Senha:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Senha:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Confirmar senha:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));
        jPanel1.add(jTNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 217, -1));
        jPanel1.add(jTEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 217, -1));
        jPanel1.add(jTBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 217, -1));
        jPanel1.add(jTMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 217, -1));
        jPanel1.add(jTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 217, -1));

        jBCancelar.setBackground(new java.awt.Color(51, 51, 51));
        jBCancelar.setForeground(new java.awt.Color(204, 204, 204));
        jBCancelar.setText("Cancelar");
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBCancelarMouseExited(evt);
            }
        });
        jPanel1.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 120, 50));

        jBConcluir.setBackground(new java.awt.Color(51, 51, 51));
        jBConcluir.setForeground(new java.awt.Color(204, 204, 204));
        jBConcluir.setText("Concluir");
        jBConcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBConcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBConcluirMouseExited(evt);
            }
        });
        jBConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jBConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 120, 50));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 10, 50));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Primeiro Acesso");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 10, 50));
        jPanel1.add(jPSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 200, -1));
        jPanel1.add(jPConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 200, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("E-mail:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));
        jPanel1.add(jTEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 217, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcluirActionPerformed
        String status = null;

        if ("".equals(jTNome.getText())) {
            jTNome.setBorder(BorderFactory.createEtchedBorder(Color.RED, Color.RED));
            status = "Vazio";
        } else {
            jTNome.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }
        
         if ("".equals(jTEmail.getText())) {
            jTEmail.setBorder(BorderFactory.createEtchedBorder(Color.RED, Color.RED));
            status = "Vazio";
        } else {
            jTEmail.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }

        if ("".equals(jTEndereco.getText())) {
            jTEndereco.setBorder(BorderFactory.createEtchedBorder(Color.RED, Color.RED));
            status = "Vazio";
        } else {
            jTEndereco.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }

        if ("".equals(jTBairro.getText())) {
            jTBairro.setBorder(BorderFactory.createEtchedBorder(Color.RED, Color.RED));
            status = "Vazio";
        } else {
            jTBairro.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }

        if ("".equals(jTMunicipio.getText())) {
            jTMunicipio.setBorder(BorderFactory.createEtchedBorder(Color.RED, Color.RED));
            status = "Vazio";
        } else {
            jTMunicipio.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }

        if ("".equals(jTNumero.getText())) {
            jTNumero.setBorder(BorderFactory.createEtchedBorder(Color.RED, Color.RED));
            status = "Vazio";
        } else {
            jTNumero.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }
        
        if ("".equals(jPConfirmarSenha.getText())) {
            jPConfirmarSenha.setBorder(BorderFactory.createEtchedBorder(Color.RED, Color.RED));
            status = "Vazio";
        } else {
            jPConfirmarSenha.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }
        
        if ("".equals(jPSenha.getText())) {
            jPSenha.setBorder(BorderFactory.createEtchedBorder(Color.RED, Color.RED));
            status = "Vazio";
        } else {
            jPSenha.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }
        
        if (jPSenha.getText().equals(jPConfirmarSenha.getText())){
            DAOAcesso daoAcesso = new DAOAcesso();
            DAOSenha daoSenha = new DAOSenha();
            
            String nome = jTNome.getText();
            String email = jTNome.getText();
            String endereco = jTNome.getText();
            String bairro = jTNome.getText();
            String municipio = jTNome.getText();
            int numero = Integer.parseInt(jTNumero.getText());
            String senha = jTNome.getText();
            
            try{
                daoAcesso.cadastrarCacesso(nome, endereco, bairro, municipio, numero, email, senha);
                jFrmSenha jFrmSenha = new jFrmSenha();
                jFrmSenha.setVisible(true);
                dispose();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane, "Erro na conexão com o banco: " + ex.getMessage());
            }
            
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "As senhas não conferem!");
            jPSenha.setText("");
            jPConfirmarSenha.setText("");
            jPSenha.requestFocus();
        }

        if("Vazio".equals(status)){
            JOptionPane.showMessageDialog(rootPane, "Os campos em vermelho são obrigatórios!");
        }
    }//GEN-LAST:event_jBConcluirActionPerformed

    private void jBConcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConcluirMouseEntered
        // TODO add your handling code here:
        jBConcluir.setBackground(new java.awt.Color(0,51,255));
    }//GEN-LAST:event_jBConcluirMouseEntered

    private void jBConcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConcluirMouseExited
        // TODO add your handling code here:
        jBConcluir.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBConcluirMouseExited

    private void jBCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseEntered
        // TODO add your handling code here:
        jBCancelar.setBackground(new java.awt.Color(255,51,51));
    }//GEN-LAST:event_jBCancelarMouseEntered

    private void jBCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseExited
        // TODO add your handling code here:
        jBCancelar.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBCancelarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmPrimeiroAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmPrimeiroAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmPrimeiroAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmPrimeiroAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmPrimeiroAcesso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPConfirmarSenha;
    private javax.swing.JPasswordField jPSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTEndereco;
    private javax.swing.JTextField jTMunicipio;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNumero;
    // End of variables declaration//GEN-END:variables
}
