-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 14:24:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ExercicioJuncao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ExercicioJuncao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ExercicioJuncao` ;
USE `ExercicioJuncao` ;

-- -----------------------------------------------------
-- Table `ExercicioJuncao`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicioJuncao`.`Telefone` (
  `cdtelefone` INT NOT NULL,
  `ddd` INT NULL,
  `ntelefone` INT NULL,
  PRIMARY KEY (`cdtelefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExercicioJuncao`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicioJuncao`.`Endereco` (
  `cdendereco` INT NOT NULL,
  `dsendereco` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `Telefone_cdtelefone` INT NOT NULL,
  PRIMARY KEY (`cdendereco`, `Telefone_cdtelefone`),
  INDEX `fk_Endereco_Telefone1_idx` (`Telefone_cdtelefone` ASC),
  CONSTRAINT `fk_Endereco_Telefone1`
    FOREIGN KEY (`Telefone_cdtelefone`)
    REFERENCES `ExercicioJuncao`.`Telefone` (`cdtelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExercicioJuncao`.`Assinante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicioJuncao`.`Assinante` (
  `cdassinante` INT NOT NULL,
  `nmassinante` VARCHAR(45) NULL,
  `Endereco_cdendereco` INT NOT NULL,
  PRIMARY KEY (`cdassinante`, `Endereco_cdendereco`),
  INDEX `fk_Assinante_Endereco1_idx` (`Endereco_cdendereco` ASC),
  CONSTRAINT `fk_Assinante_Endereco1`
    FOREIGN KEY (`Endereco_cdendereco`)
    REFERENCES `ExercicioJuncao`.`Endereco` (`cdendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExercicioJuncao`.`Ramoatividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicioJuncao`.`Ramoatividade` (
  `cdramo` INT NOT NULL,
  `dsramo` VARCHAR(45) NULL,
  `Assinante_cdassinante` INT NOT NULL,
  PRIMARY KEY (`cdramo`, `Assinante_cdassinante`),
  INDEX `fk_Ramoatividade_Assinante_idx` (`Assinante_cdassinante` ASC),
  CONSTRAINT `fk_Ramoatividade_Assinante`
    FOREIGN KEY (`Assinante_cdassinante`)
    REFERENCES `ExercicioJuncao`.`Assinante` (`cdassinante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExercicioJuncao`.`Tipoassinante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicioJuncao`.`Tipoassinante` (
  `cdtipo` INT NOT NULL,
  `dstipo` VARCHAR(45) NULL,
  `Assinante_cdassinante` INT NOT NULL,
  PRIMARY KEY (`cdtipo`, `Assinante_cdassinante`),
  INDEX `fk_Tipoassinante_Assinante1_idx` (`Assinante_cdassinante` ASC),
  CONSTRAINT `fk_Tipoassinante_Assinante1`
    FOREIGN KEY (`Assinante_cdassinante`)
    REFERENCES `ExercicioJuncao`.`Assinante` (`cdassinante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExercicioJuncao`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicioJuncao`.`Municipio` (
  `cdmunicipio` INT NOT NULL,
  `dsmunicipio` VARCHAR(45) NULL,
  `Endereco_cdendereco` INT NOT NULL,
  PRIMARY KEY (`cdmunicipio`, `Endereco_cdendereco`),
  INDEX `fk_Municipio_Endereco1_idx` (`Endereco_cdendereco` ASC),
  CONSTRAINT `fk_Municipio_Endereco1`
    FOREIGN KEY (`Endereco_cdendereco`)
    REFERENCES `ExercicioJuncao`.`Endereco` (`cdendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Exercícios de SQL(Junções)

-- A)
select A.nmassinante, E.dsendereco, E.complemento, E.bairro, E.cep, T.ntelefone from Assinante as A
inner join Endereco as E on (A.Endereco_cdendereco = E.cdendereco)
inner join Telefone as T on (E.Telefone_cdtelefone = T.cdtelefone);

-- B) 
select A.nmassinante, R.dsramo from Assinante as A
inner join Ramoatividade as R on (A.cdassinante = R.Assinante_cdassinante)
order by R.dsramo and A.nmassinante;

-- C) 
select A.nmassinante from Assinante as A
inner join Endereco as E on (A.Endereco_cdendereco = E.cdendereco)
inner join Municipio as M on(E.cdendereco = M.Endereco_cdendereco)
Where M.dsmunicipio = "Pelotas" and E.complemento = "Residencia";

-- D)
select A.nmassinante from Assinante as A
inner join Endereco as E on (A.Endereco_cdendereco = E.cdendereco)
inner join Telefone as T on (E.Telefone_cdtelefone = T.cdtelefone)
group by A.nmassinante having count(T.ntelefone) > 3;

-- E)
select A.nmassinante, T.ntelefone, TA.dstipo from Assinante as A
inner join Endereco as E on (A.Endereco_cdendereco = E.cdendereco)
inner join Telefone as T on (E.Telefone_cdtelefone = T.cdtelefone)
inner join Tipoassinante as TA on (A.cdassinante = TA.Assinante_cdassinante)
inner join Municipio as M on (E.cdendereco = M.Endereco_cdendereco)
where M.dsmunicipio = "Natal" or M.dsmunicipio = "Joao Camara" and TA.dstipo = "Comercial";