/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.PacienteDAO;
import Model.PacienteModel;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno.Tarde
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTPlano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCGenero = new javax.swing.JComboBox<>();
        jBSair = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();
        jBPesquisar = new javax.swing.JButton();
        jTNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("TESTE LP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 28, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, -1, -1));

        jTPlano.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 235, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Descrição:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Preço:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Gênero:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jCGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outros" }));
        jPanel1.add(jCGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jBSair.setBackground(new java.awt.Color(0, 102, 255));
        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });
        jPanel1.add(jBSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 290, -1, -1));

        jBCadastrar.setBackground(new java.awt.Color(0, 102, 255));
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jBPesquisar.setBackground(new java.awt.Color(0, 102, 255));
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jBPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jTNome.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 235, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:     
        String status = null;

        if (jTNome.getText().isEmpty()) {
            jTNome.setBorder(BorderFactory.createEtchedBorder(Color.BLUE, Color.BLUE));
            status = "Vazio";
        } else {
            jTNome.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }
        
        if (jTPlano.getText().isEmpty()) {
            jTPlano.setBorder(BorderFactory.createEtchedBorder(Color.BLUE, Color.BLUE));
            status = "Vazio";
        } else {
            jTPlano.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }

        if(status == null){
            String nome = jTNome.getText();
            String plano = jTPlano.getText();
            String genero = String.valueOf(jCGenero.getSelectedItem());

            PacienteModel pacienteModel = new PacienteModel();
            pacienteModel.setNome(nome);
            pacienteModel.setPlano(plano);
            pacienteModel.setGenero(genero);

            try{
                PacienteDAO pacienteDAO = new PacienteDAO();
                int response = pacienteDAO.cadastrarPaciente(pacienteModel);
                
                if(response != -1){
                    JOptionPane.showMessageDialog(rootPane, "Cadastro efetuado.");
                }else{
                    JOptionPane.showMessageDialog(rootPane, "ERRO: Cadastro negado.");
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane, "Erro na conexão com o banco: " + ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Os campos em vermelho são obrigatórios!");
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:
        try{
            String nome = jTNome.getText();
            
            PacienteDAO pacienteDAO = new PacienteDAO();
            PacienteModel pacienteModel = pacienteDAO.pesquisarPaciente(nome);
            
            if(pacienteModel != null){
                jTNome.setText(pacienteModel.getNome());
                jTPlano.setText(pacienteModel.getPlano());
                jCGenero.setSelectedItem(pacienteModel.getGenero());
            }else{
                System.out.println("ERRO: " + pacienteModel);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Nome inexistente" + ex.getMessage());
            jTPlano.setText("");
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBSair;
    private javax.swing.JComboBox<String> jCGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTPlano;
    // End of variables declaration//GEN-END:variables
}
