-- MySQL Script generated by MySQL Workbench
-- Tue May  7 14:33:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ConsultarADM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ConsultarADM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ConsultarADM` ;
USE `ConsultarADM` ;

-- -----------------------------------------------------
-- Table `ConsultarADM`.`Cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsultarADM`.`Cadastro` (
  `idAdm` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `CPF` VARCHAR(14) NULL,
  PRIMARY KEY (`idAdm`))
ENGINE = InnoDB;
select * from Cadastro;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
