-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 16:43:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzaria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzaria` ;

-- -----------------------------------------------------
-- Table `Pizzaria`.`Tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Tamanho` (
  `idTamanho` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Desconto` FLOAT NULL,
  PRIMARY KEY (`idTamanho`))
ENGINE = InnoDB;
select * from Tamanho;

-- -----------------------------------------------------
-- Table `Pizzaria`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Pizza` (
  `idPizza` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Preco` FLOAT NULL,
  `Personalizado` VARCHAR(30) NULL,
  PRIMARY KEY (`idPizza`))
ENGINE = InnoDB;
select * from Pizza;

-- -----------------------------------------------------
-- Table `Pizzaria`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Data` DATE NULL,
  `Hora` TIME NULL,
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB;
select * from Pedido;

-- -----------------------------------------------------
-- Table `Pizzaria`.`PizzaPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`PizzaPedido` (
  `IdPizzaPedido` INT NOT NULL,
  `Quantidade` VARCHAR(45) NULL,
  `Pizza_idPizza` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Tamanho_idTamanho` INT NOT NULL,
  PRIMARY KEY (`IdPizzaPedido`),
  INDEX `fk_PizzaPedido_Pizza_idx` (`Pizza_idPizza` ASC) ,
  INDEX `fk_PizzaPedido_Pedido1_idx` (`Pedido_idPedido` ASC) ,
  INDEX `fk_PizzaPedido_Tamanho1_idx` (`Tamanho_idTamanho` ASC) ,
  CONSTRAINT `fk_PizzaPedido_Pizza`
    FOREIGN KEY (`Pizza_idPizza`)
    REFERENCES `Pizzaria`.`Pizza` (`idPizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PizzaPedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Pizzaria`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PizzaPedido_Tamanho1`
    FOREIGN KEY (`Tamanho_idTamanho`)
    REFERENCES `Pizzaria`.`Tamanho` (`idTamanho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
select * from PizzaPedido;
drop table PizzaPedido;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from Cliente;