-- MySQL Script generated by MySQL Workbench
-- Mon May  6 14:21:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDEstoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDEstoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDEstoque` ;
USE `BDEstoque` ;

-- -----------------------------------------------------
-- Table `BDEstoque`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDEstoque`.`Cliente` (
  `Codigo` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Sexo` VARCHAR(1) NULL,
  `DataNasc` DATE NULL,
  `Profissao` VARCHAR(40) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDEstoque`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDEstoque`.`Pedido` (
  `NumeroPedido` INT NOT NULL,
  `CodigoCliente` INT NULL,
  `DataPed` DATE NULL,
  `TotalPedido` DECIMAL(10,2) NULL,
  `Cliente_Codigo` INT NOT NULL,
  PRIMARY KEY (`NumeroPedido`),
  INDEX `fk_Pedido_Cliente_idx` (`Cliente_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_Codigo`)
    REFERENCES `BDEstoque`.`Cliente` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDEstoque`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDEstoque`.`Produto` (
  `NumeroProd` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Valor` DECIMAL(10,2) NULL,
  `Validade` DATE NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`NumeroProd`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDEstoque`.`Itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDEstoque`.`Itens` (
  `NumeroItem` INT NOT NULL,
  `Quantidade` INT NULL,
  `ValorItem` DECIMAL(10,2) NULL,
  `Produto_NumeroProd` INT NOT NULL,
  `Pedido_NumeroPedido` INT NOT NULL,
  PRIMARY KEY (`NumeroItem`),
  INDEX `fk_Itens_Produto1_idx` (`Produto_NumeroProd` ASC) VISIBLE,
  INDEX `fk_Itens_Pedido1_idx` (`Pedido_NumeroPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Itens_Produto1`
    FOREIGN KEY (`Produto_NumeroProd`)
    REFERENCES `BDEstoque`.`Produto` (`NumeroProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_Pedido1`
    FOREIGN KEY (`Pedido_NumeroPedido`)
    REFERENCES `BDEstoque`.`Pedido` (`NumeroPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from Cliente;