/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ProdutoDAO;
import Model.ProdutoModel;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno.Tarde
 */
public class Tela01 extends javax.swing.JFrame {
ProdutoDAO ProdutoDAO = new ProdutoDAO();
    /**
     * Creates new form Tela01
     */
    public Tela01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LucroRadio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PrecoTxt = new javax.swing.JTextField();
        DescricaoTxt = new javax.swing.JTextField();
        SalvarBtn = new javax.swing.JButton();
        PesquisarBtn = new javax.swing.JButton();
        SairBtn = new javax.swing.JButton();
        CancelarBtn = new javax.swing.JButton();
        Lucro10 = new javax.swing.JRadioButton();
        Lucro5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Teste LP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Lucro:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel3.setText("Descrição:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Preço Unitario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        jPanel1.add(PrecoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, -1));
        jPanel1.add(DescricaoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, -1));

        SalvarBtn.setText("Salvar");
        SalvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SalvarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 90, -1));

        PesquisarBtn.setText("Pesquisar");
        PesquisarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PesquisarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        SairBtn.setText("Sair");
        SairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SairBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 100, -1));

        CancelarBtn.setText("Cancelar");
        CancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, -1));

        LucroRadio.add(Lucro10);
        Lucro10.setText("10%");
        jPanel1.add(Lucro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        LucroRadio.add(Lucro5);
        Lucro5.setText("5%");
        jPanel1.add(Lucro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesquisarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarBtnActionPerformed
        // TODO add your handling code here:
        try{
            String descricao = DescricaoTxt.getText();

            ProdutoDAO produtoDAO = new ProdutoDAO();
            ProdutoModel produtoModel = produtoDAO.pesquisarProduto(descricao);
            
            if(produtoModel != null){
                DescricaoTxt.setText(produtoModel.getDescricao());
                PrecoTxt.setText(String.valueOf(produtoModel.getPreco()));
            }else{
                System.out.println("ERRO: " + produtoModel);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Nome inexistente" + ex.getMessage());
            DescricaoTxt.setText("");
        }
    }//GEN-LAST:event_PesquisarBtnActionPerformed

    private void SalvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBtnActionPerformed
        // TODO add your handling code here:
           String status = null;

        if (DescricaoTxt.getText().isEmpty()) {
            DescricaoTxt.setBorder(BorderFactory.createEtchedBorder(Color.BLUE, Color.BLUE));
            status = "Vazio";
        } else {
            DescricaoTxt.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }
        
        if (PrecoTxt.getText().isEmpty()) {
            PrecoTxt.setBorder(BorderFactory.createEtchedBorder(Color.BLUE, Color.BLUE));
            status = "Vazio";
        } else {
            PrecoTxt.setBorder(BorderFactory.createBevelBorder(WIDTH, Color.LIGHT_GRAY, Color.LIGHT_GRAY));
        }

        if(status == null){
            String descricao = DescricaoTxt.getText();
            Double preco = Double.valueOf(PrecoTxt.getText());
            
            String lucro = null;
            
            if(Lucro10.isSelected()){
               lucro = "10%";
            }
            if(Lucro5.isSelected()){
               lucro = "5%";
            }

            
            ProdutoModel ProdutoModel = new ProdutoModel();
            ProdutoModel.setDescricao(descricao);
            ProdutoModel.setPreco(preco);
            ProdutoModel.setLucro(lucro);

            try{
                
                ProdutoDAO ProdutoDAO = new ProdutoDAO();
                int response = ProdutoDAO.cadastrarProduto(ProdutoModel);
                
                if(response != -1){
                    JOptionPane.showMessageDialog(rootPane, "Cadastro efetuado.");
                }else{
                    JOptionPane.showMessageDialog(rootPane, "ERRO: Cadastro negado.");
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane, "Erro na conexão com o banco: " + ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Os campos em vermelho são obrigatórios!");
        }
        
    }//GEN-LAST:event_SalvarBtnActionPerformed

    private void SairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairBtnActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_SairBtnActionPerformed

    private void CancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBtnActionPerformed
        DescricaoTxt.setText("");
        PrecoTxt.setText("");

    }//GEN-LAST:event_CancelarBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarBtn;
    private javax.swing.JTextField DescricaoTxt;
    private javax.swing.JRadioButton Lucro10;
    private javax.swing.JRadioButton Lucro5;
    private javax.swing.ButtonGroup LucroRadio;
    private javax.swing.JButton PesquisarBtn;
    private javax.swing.JTextField PrecoTxt;
    private javax.swing.JButton SairBtn;
    private javax.swing.JButton SalvarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
