-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 14:19:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bdcreche
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bdcreche
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bdcreche` ;
USE `Bdcreche` ;

-- -----------------------------------------------------
-- Table `Bdcreche`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bdcreche`.`Aluno` (
  `Matricula` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Idade` INT NOT NULL,
  `Nomeresponsavel` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Matricula`),
  UNIQUE INDEX `Matricula_UNIQUE` (`Matricula` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
