-- MySQL Script generated by MySQL Workbench
-- Tue May 14 14:15:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CadastrarADM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CadastrarADM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CadastrarADM` ;
USE `CadastrarADM` ;

-- -----------------------------------------------------
-- Table `CadastrarADM`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CadastrarADM`.`Cliente` (
  `idCliente` INT auto_increment,
  `Login` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;
select * from Cliente;
drop table Cliente;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

