
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JCBatata = new javax.swing.JCheckBox();
        JCHamburguer = new javax.swing.JCheckBox();
        JCCoca = new javax.swing.JCheckBox();
        JCCheesebacon = new javax.swing.JCheckBox();
        JCPizza = new javax.swing.JCheckBox();
        JBTotal = new javax.swing.JButton();
        JBSair = new javax.swing.JButton();
        JBLimpar = new javax.swing.JButton();
        JTextTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jLabel1.setText("CARDÁPIO");

        JCBatata.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        JCBatata.setText("Batata");
        JCBatata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBatataActionPerformed(evt);
            }
        });

        JCHamburguer.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        JCHamburguer.setText("Hamburguer");
        JCHamburguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCHamburguerActionPerformed(evt);
            }
        });

        JCCoca.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        JCCoca.setText("Coca-Cola");
        JCCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCCocaActionPerformed(evt);
            }
        });

        JCCheesebacon.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        JCCheesebacon.setText("Cheesebacon");
        JCCheesebacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCCheesebaconActionPerformed(evt);
            }
        });

        JCPizza.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        JCPizza.setText("Pizza");
        JCPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCPizzaActionPerformed(evt);
            }
        });

        JBTotal.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        JBTotal.setText("Total");
        JBTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTotalActionPerformed(evt);
            }
        });

        JBSair.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        JBSair.setText("Sair");
        JBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSairActionPerformed(evt);
            }
        });

        JBLimpar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        JBLimpar.setText("Limpar");
        JBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimparActionPerformed(evt);
            }
        });

        JTextTotal.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Total a pagar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JCBatata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBTotal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JCCheesebacon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBSair))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCHamburguer)
                                    .addComponent(JCCoca)
                                    .addComponent(JCPizza))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JBLimpar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTextTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(20, 20, 20)))))))
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCBatata))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(JBTotal)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCHamburguer)
                        .addGap(18, 18, 18)
                        .addComponent(JCCoca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(JBLimpar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JCCheesebacon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JCPizza))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(JBSair)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimparActionPerformed
        // TODO add your handling code here:
        JCBatata.setSelected(false);
        JCHamburguer.setSelected(false);
        JCCoca.setSelected(false);
        JCCheesebacon.setSelected(false);
        JCPizza.setSelected(false);
        JTextTotal.setText("");
    }//GEN-LAST:event_JBLimparActionPerformed

    private void JBTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTotalActionPerformed
        // TODO add your handling code here:
        double batata=0, Hamburguer=0, Coca=0, Cheesebacon=0, Pizza=0, total=0;
        
        if (JCBatata.isSelected()){
            batata = 20;
        }
        if (JCHamburguer.isSelected()){
            Hamburguer = 15;
        }
        if (JCCoca.isSelected()){
            Coca = 7;
        }
        if (JCCheesebacon.isSelected()){
            Cheesebacon = 13;
        }
        if (JCPizza.isSelected()){
            Pizza = 45;
        }   
        
        total = batata + Hamburguer + Coca + Cheesebacon + Pizza;
        JTextTotal.setText(Double.toString(total));
    }//GEN-LAST:event_JBTotalActionPerformed

    private void JBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JBSairActionPerformed

    private void JCBatataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBatataActionPerformed
        // TODO add your handling code here:
        if (JCBatata.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Adicionado 20,00R$");
        }
    }//GEN-LAST:event_JCBatataActionPerformed

    private void JCHamburguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCHamburguerActionPerformed
        // TODO add your handling code here:
        if (JCHamburguer.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Adicionado 15,00R$");
        }
    }//GEN-LAST:event_JCHamburguerActionPerformed

    private void JCCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCCocaActionPerformed
        // TODO add your handling code here:
        if (JCCoca.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Adicionado 7,00R$");
        }
    }//GEN-LAST:event_JCCocaActionPerformed

    private void JCCheesebaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCCheesebaconActionPerformed
        // TODO add your handling code here:
        if (JCCheesebacon.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Adicionado 13,00R$");
        }
    }//GEN-LAST:event_JCCheesebaconActionPerformed

    private void JCPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCPizzaActionPerformed
        // TODO add your handling code here:
        if (JCPizza.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Adicionado 45,00R$");
        }
    }//GEN-LAST:event_JCPizzaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBLimpar;
    private javax.swing.JButton JBSair;
    private javax.swing.JButton JBTotal;
    private javax.swing.JCheckBox JCBatata;
    private javax.swing.JCheckBox JCCheesebacon;
    private javax.swing.JCheckBox JCCoca;
    private javax.swing.JCheckBox JCHamburguer;
    private javax.swing.JCheckBox JCPizza;
    private javax.swing.JTextField JTextTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
