-- MySQL Script generated by MySQL Workbench
-- Thu Aug 22 14:04:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjetoTardeExemplo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjetoTardeExemplo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoTardeExemplo` ;
USE `ProjetoTardeExemplo` ;

-- -----------------------------------------------------
-- Table `ProjetoTardeExemplo`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoTardeExemplo`.`Cliente` (
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Municipio` VARCHAR(45) NOT NULL,
  `Profissao` VARCHAR(45),
  `Genero` VARCHAR(45),
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoTardeExemplo`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoTardeExemplo`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `Nivel` VARCHAR(45),
  `Senha` VARCHAR(45) NOT NULL,
  `Cliente_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogin`, `Cliente_Email`),
  INDEX `fk_Login_Cliente_idx` (`Cliente_Email` ASC),
  CONSTRAINT `fk_Login_Cliente`
    FOREIGN KEY (`Cliente_Email`)
    REFERENCES `ProjetoTardeExemplo`.`Cliente` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
